// (C) ArMaTeC 2009, armatec0@gmail.com ";
// Released under Creative Commons Attribution-Noncommercial-Share Alike 2.0 UK:England & Wales License ";
// http://creativecommons.org/licenses/by-nc-sa/2.0/uk/";
_ammobox = _this select 0;
_waitrnd = 0;
_waitrnd = ( 300 + round( random 600 ) );
clearWeaponCargo _ammobox;
clearMagazineCargo _ammobox;

 clearweaponcargo castlebox;
 clearmagazinecargo castlebox;

 castlebox addweaponcargo ["ACRE_PRC152",10];
 castlebox addweaponcargo ["ACE_Earplugs",10];
 castlebox addweaponcargo ["ItemGPS",5];
 castlebox addweaponcargo ["ACRE_PRC117F",3];
 castlebox addweaponcargo ["ACRE_PRC119",3];
 castlebox addweaponcargo ["ACE_ANPRC77",3];
 castlebox addweaponcargo ["AK_107_GL_pso",1];
 castlebox addweaponcargo ["ACE_AK74M_Kobra",1];
 castlebox addweaponcargo ["ACE_AKS74_UN",1];
 castlebox addweaponcargo ["ACE_Val_PSO",1];
 castlebox addweaponcargo ["ACE_oc14gl",2];
 castlebox addweaponcargo ["ACE_oc14sdsp",1];
 castlebox addweaponcargo ["M14_EP1",1];
 castlebox addweaponcargo ["ACE_M4A1_Aim_SD",1];
 castlebox addweaponcargo ["ACE_SOC_M4A1_GL_UP",1];
 castlebox addweaponcargo ["SCAR_L_CQC_Holo",1];
 castlebox addweaponcargo ["ACE_ParachutePack",10];
 castlebox addweaponcargo ["ACE_P159_RD54",2];
 castlebox addweaponcargo ["ACE_ParachuteRoundPack",10];
 castlebox addweaponcargo ["Binocular",7];
 castlebox addweaponcargo ["NVGoggles",5];
 castlebox addweaponcargo ["ACE_Flaregun",2];
 castlebox addweaponcargo ["ACE_ALICE_Backpack",7];
 castlebox addweaponcargo ["ACE_CharliePack_WMARPAT",6];
 castlebox addweaponcargo ["ACE_Coyote_Pack_Multicam",4];
 castlebox addweaponcargo ["ACE_Rucksack_MOLLE_Green",6];
 castlebox addweaponcargo ["ACE_Rucksack_RD54",5];
 castlebox addmagazinecargo ["ACE_DSHKM_CSWDM",2];
 castlebox addmagazinecargo ["ACE_TOW_CSWDM",2];
 castlebox addmagazinecargo ["30Rnd_545x39_AK",20];
 castlebox addmagazinecargo ["30Rnd_545x39_AKSD",20];
 castlebox addmagazinecargo ["20Rnd_9x39_SP5_VSS",10];
 castlebox addmagazinecargo ["ACE_20Rnd_9x39_SP6_VSS",10];
 castlebox addmagazinecargo ["1Rnd_HE_GP25",5];
 castlebox addmagazinecargo ["ACE_20Rnd_9x39_B_SP6_OC14",10];
 castlebox addmagazinecargo ["ACE_20Rnd_9x39_S_SP6_OC14",10];
 castlebox addmagazinecargo ["ACE_20Rnd_9x39_S_OC14",10];
 castlebox addmagazinecargo ["ACE_20Rnd_762x51_B_M14",15];
 castlebox addmagazinecargo ["ACE_30Rnd_556x45_S_Stanag",38];
 castlebox addmagazinecargo ["ACE_30Rnd_556x45_SB_S_Stanag",15];
 castlebox addmagazinecargo ["ACE_30Rnd_556x45_T_Stanag",14];
 castlebox addmagazinecargo ["30Rnd_556x45_StanagSD",15];
 castlebox addmagazinecargo ["1Rnd_HE_M203",5];
 castlebox addmagazinecargo ["ACE_Bandage",18];
 castlebox addmagazinecargo ["ACE_Epinephrine",11];
 castlebox addmagazinecargo ["ACE_LargeBandage",20];
 castlebox addmagazinecargo ["ACE_Medkit",5];
 castlebox addmagazinecargo ["ACE_Morphine",10];
 castlebox addmagazinecargo ["ACE_Plasma",20];
 castlebox addmagazinecargo ["ACE_Tourniquet",15];
 castlebox addmagazinecargo ["IR_Strobe_Marker",15];
 castlebox addmagazinecargo ["ACE_Rope_M_120",11];
 castlebox addmagazinecargo ["ACE_Rope_M_90",9];
 castlebox addmagazinecargo ["ACE_Flashbang",8];
 castlebox addmagazinecargo ["BAF_L109A1_HE",2];
 castlebox addmagazinecargo ["ACE_M7A3",14];
 castlebox addmagazinecargo ["PipeBomb",3];
 castlebox addmagazinecargo ["SmokeShell",9];
 castlebox addmagazinecargo ["SmokeShellBlue",8];
 castlebox addmagazinecargo ["ACE_TORCH_C",3];
 castlebox addmagazinecargo ["ACE_SSRed_FG",12];
 castlebox addmagazinecargo ["ACE_SSGreen_FG",8];
 castlebox addmagazinecargo ["ACE_SSWhite_FG",7];

_wait = 60 + _waitrnd;
sleep _wait;
_reWait = _time + 60;
_ammobox setdammage 0;
sleep 1.0;
ammoboxtr = [ _ammobox ] execVM "AmmoRefill_static.sqf";